"""Retire a branch that should never have been one.

    python -m scripts.retire_branch --code HO --move-documents-to FC
    python -m scripts.retire_branch --code HO --move-documents-to FC --yes

The case this exists for: "Head Office" was seeded into the branch list, which made the company's
own head office look like a shop. It is not. Head office is the Cloud — it holds the godown, the
catalog and the company view, and it does not trade over a counter. A shop standing next door to
head office is a branch like any other: its own server, its own database, its own code on its own
bills, still trading when the line to head office is down.

Leaving the row in place was not cosmetic. Every company-wide total counted that shop twice the
moment a real branch started reporting the same trade.

**Nothing is thrown away silently.** Requisitions and transfers are *moved* to a real branch, not
deleted — they record stock that genuinely left the godown, and that happened whatever the
destination row was called. Only the reported statistics are removed, because those are a
duplicate of what the real branch reports, and they regenerate from sync anyway.

Prints the full plan and refuses to touch anything without --yes.
"""
from __future__ import annotations

import argparse
import asyncio

from tortoise import Tortoise

from app.core.config import TORTOISE_ORM
from app.models import (
    Branch,
    BranchCashierStat,
    BranchCreditCustomer,
    BranchDailyStat,
    BranchDiscountOverride,
    BranchHourlyStat,
    BranchProductStat,
    BranchProductStock,
    BranchReturn,
    BranchSnapshotRun,
    BranchStockAlert,
    BranchTenderStat,
    BranchTillClose,
    Requisition,
    SyncInboxEvent,
    SyncRun,
    Transfer,
)

# Reported figures. Duplicates of whatever the real branch reports, and regenerated by sync.
STAT_MODELS = (
    BranchDailyStat, BranchCashierStat, BranchProductStat, BranchStockAlert,
    BranchHourlyStat, BranchTillClose, BranchTenderStat, BranchDiscountOverride,
    BranchReturn, BranchCreditCustomer, BranchProductStock, BranchSnapshotRun,
    SyncInboxEvent, SyncRun,
)
# Business documents. Moved, never deleted.
DOCUMENT_MODELS = (Requisition, Transfer)


async def retire(code: str, move_to: str | None, confirm: bool) -> None:
    branch = await Branch.get_or_none(code=code.upper())
    if not branch:
        raise SystemExit(f"No branch registered with code {code.upper()}.")
    if branch.verified_at is not None:
        raise SystemExit(
            f"{branch.code} is verified and paired with a live branch server. Un-pair it on the "
            "Cloud first — retiring a branch a server is still syncing to would strand that server."
        )

    print(f"\n  Retiring {branch.code} — {branch.name}\n")

    print("  Documents to move (kept, re-pointed):")
    doc_counts = {}
    for model in DOCUMENT_MODELS:
        n = await model.filter(branch=branch).count()
        doc_counts[model] = n
        print(f"    {model.__name__:<22} {n}")

    destination = None
    if any(doc_counts.values()):
        if not move_to:
            raise SystemExit(
                "\n  This branch has documents against it. Pass --move-documents-to <CODE> to say "
                "where they should go."
            )
        destination = await Branch.get_or_none(code=move_to.upper())
        if not destination:
            raise SystemExit(f"\n  No branch with code {move_to.upper()} to move documents to.")
        if destination.id == branch.id:
            raise SystemExit("\n  Can't move a branch's documents to itself.")
        print(f"    -> moving to {destination.code} — {destination.name}")

    print("\n  Reported figures to remove (duplicates; sync regenerates a real branch's):")
    total_stats = 0
    for model in STAT_MODELS:
        n = await model.filter(branch=branch).count()
        total_stats += n
        if n:
            print(f"    {model.__name__:<22} {n}")
    if not total_stats:
        print("    (none)")

    if not confirm:
        print("\n  Nothing changed. Re-run with --yes to apply.\n")
        return

    for model in DOCUMENT_MODELS:
        if doc_counts[model]:
            await model.filter(branch=branch).update(branch_id=destination.id)
    for model in STAT_MODELS:
        await model.filter(branch=branch).delete()
    await branch.delete()

    print(f"\n  Done. {branch.code} is gone; {sum(doc_counts.values())} document(s) kept.")
    print("  Branches now on the Cloud:")
    for b in await Branch.all().order_by("code"):
        mark = "verified" if b.verified_at else "not verified"
        print(f"    {b.code:<6} {b.name:<24} {mark}")
    print()


async def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--code", required=True, help="Branch code to retire, e.g. HO")
    ap.add_argument("--move-documents-to", help="Branch code that inherits its requisitions and transfers")
    ap.add_argument("--yes", action="store_true", help="Actually apply it")
    args = ap.parse_args()

    await Tortoise.init(config=TORTOISE_ORM)
    try:
        await retire(args.code, args.move_documents_to, args.yes)
    finally:
        await Tortoise.close_connections()


if __name__ == "__main__":
    asyncio.run(main())
